name: issue-fixing

on: [push]

jobs:
  job-centos_7_5:
    runs-on: ubuntu-latest
    container: centos:7.5.1804
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: install base software
        run: yum install -y wget gcc-c++

      - name: install gcc filter
        uses: Trass3r/setup-cpp@master

      - name: compile
        run: |
          make clean
          make all

      - name: run normal
        run: |
          make run
      
      - name: run after upx lib
        run: |
          make upx_lib
          make run
